"""
Test 03: Sensor Noise Analysis
Computes noise statistics per channel and compares to sim noise model.

Usage: python analyze.py [--results results.json] [--out report.md]
"""
import json
import argparse
import numpy as np
from pathlib import Path


def analyze_stream(samples, channel_names=None):
    """Compute per-channel mean, std, p95, p99 for a list of samples.
    samples: list of scalars, lists, or dicts."""
    arr = np.array(samples)
    if arr.ndim == 1:
        arr = arr[:, None]
    elif arr.ndim > 2:
        arr = arr.reshape(len(samples), -1)

    stats = []
    for i in range(arr.shape[1]):
        col  = arr[:, i]
        name = (channel_names[i] if channel_names and i < len(channel_names)
                else f"ch_{i}")
        stats.append({
            "channel": name,
            "mean"   : float(col.mean()),
            "std"    : float(col.std()),
            "p95"    : float(np.percentile(np.abs(col - col.mean()), 95)),
            "p99"    : float(np.percentile(np.abs(col - col.mean()), 99)),
            "min"    : float(col.min()),
            "max"    : float(col.max()),
        })
    return stats


def normality_score(samples):
    """Rough Gaussian check: kurtosis near 3 = Gaussian."""
    try:
        arr = np.array(samples).flatten()
        n   = len(arr)
        m4  = np.mean((arr - arr.mean())**4)
        s4  = arr.std()**4
        kurt = m4 / s4 if s4 > 0 else 0
        return float(kurt)   # 3 = Gaussian
    except Exception:
        return None


def main(results_path: str, out_path: str):
    with open(results_path) as f:
        r = json.load(f)

    sim_noise = r.get("sim_noise_std") or {}
    obs_names = r.get("obs_names")
    streams   = r.get("streams", {})

    lines = [
        "# Test 03 — Sensor Noise Analysis Report",
        "",
        f"**Duration**: {r['record_duration_s']}s  |  "
        f"**Rate**: {r['record_hz']} Hz  |  "
        f"**Samples**: {r['n_samples']}",
        "",
    ]

    feedback = []

    for stream_name, stream in streams.items():
        samples = stream["samples"]
        cnames  = obs_names if stream_name == "observation" else None
        stats   = analyze_stream(samples, cnames)
        kurt    = normality_score(samples)

        lines += [
            f"## {stream_name}",
            "",
            "| Channel | Mean | Std (real) | Sim Std | Ratio | p95 | p99 |",
            "|---------|------|-----------|---------|-------|-----|-----|",
        ]

        for s in stats:
            sim_std = sim_noise.get(s["channel"]) or sim_noise.get(stream_name)
            ratio   = f"{s['std'] / sim_std:.2f}x" if sim_std else "—"
            sim_str = f"{sim_std:.4f}" if sim_std else "—"
            lines.append(
                f"| {s['channel']} | {s['mean']:.4f} | {s['std']:.4f} | "
                f"{sim_str} | {ratio} | {s['p95']:.4f} | {s['p99']:.4f} |"
            )

            # Flag mismatch
            if sim_std:
                r_val = s["std"] / sim_std
                if r_val > 2.0:
                    feedback.append(
                        f"- **FB-N{len(feedback)+1} [{stream_name}/{s['channel']}]**: "
                        f"Real noise std ({s['std']:.4f}) is {r_val:.1f}x sim model "
                        f"({sim_std:.4f}). Increase `sim_noise_std.{s['channel']}` "
                        f"in deploy-config.json and retrain with domain randomization."
                    )
                elif r_val < 0.3:
                    feedback.append(
                        f"- **FB-N{len(feedback)+1} [{stream_name}/{s['channel']}]**: "
                        f"Real noise ({s['std']:.4f}) much lower than sim "
                        f"({sim_std:.4f}). Sim may be over-regularizing; "
                        f"reduce noise range to avoid over-cautious policy."
                    )

        if kurt is not None:
            kurt_note = ("≈ Gaussian" if 2.0 < kurt < 4.5 else
                         f"Non-Gaussian (kurtosis={kurt:.1f}) — consider Student-t noise model")
            lines += ["", f"*Distribution kurtosis: {kurt:.2f} — {kurt_note}*", ""]
        else:
            lines.append("")

    lines += [
        "## Design Feedback",
        "",
    ]
    if feedback:
        lines += feedback
    else:
        lines.append("- Noise distribution matches sim model. No design changes required.")

    lines += [
        "",
        "## Recommendations",
        "",
        "If real noise >> sim noise:",
        "1. Update `sim_noise_std` fields in `deploy-config.json`.",
        "2. Add noise curriculum in training: start clean, ramp to real noise level.",
        "3. Consider a state estimator / Kalman filter in the policy's observation pipeline.",
        "",
        "_Generated by analyze.py — Test 03 Sensor Noise_",
    ]

    Path(out_path).write_text("\n".join(lines))
    print(f"Report written → {out_path}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results.json")
    ap.add_argument("--out",     default="report.md")
    args = ap.parse_args()
    main(args.results, args.out)
