"""
Test 06: Speed Tracking Analysis
Evaluates tracking error per speed level, max stable speed, velocity oscillation.

Usage: python analyze.py [--results results.json] [--out report.md]
"""
import json
import argparse
import numpy as np
from pathlib import Path


def main(results_path: str, out_path: str):
    with open(results_path) as f:
        r = json.load(f)

    trials      = r["trials"]
    design_max  = r.get("design_max_speed")
    max_stable  = r.get("max_stable_speed", 0.0)
    feedback    = []

    lines = [
        "# Test 06 — Speed Tracking Analysis Report",
        "",
        f"**Hold duration**: {r['hold_duration_s']}s per speed level",
        f"**Max stable speed**: {max_stable:.2f} m/s  |  "
        f"**Design target**: {design_max or '—'} m/s",
        "",
        "## Speed Tracking Table",
        "",
        "| Target (m/s) | Achieved (m/s) | Std | Tracking Err | Fell? | Status |",
        "|-------------|----------------|-----|-------------|-------|--------|",
    ]

    for trial in trials:
        tgt   = trial["target_mps"]
        ach   = trial["achieved_mean"]
        std   = trial["achieved_std"]
        err   = trial["tracking_err"]
        fell  = trial["fell"]
        pct   = err / tgt * 100 if tgt > 0 else 0
        status = "✗ FALL" if fell else ("⚠️" if pct > 15 else "✓")
        lines.append(
            f"| {tgt:.2f} | {ach:.2f} | {std:.3f} | "
            f"{err:.3f} ({pct:.0f}%) | {'Yes' if fell else 'No'} | {status} |"
        )

    # Tracking quality summary
    stable_trials = [t for t in trials if not t["fell"]]
    if stable_trials:
        errs    = [t["tracking_err"] for t in stable_trials]
        stds    = [t["achieved_std"]  for t in stable_trials]
        mean_err= float(np.mean(errs))
        mean_std= float(np.mean(stds))

        lines += [
            "",
            f"**Mean tracking error** (stable speeds): {mean_err:.3f} m/s",
            f"**Mean velocity oscillation** (std):     {mean_std:.3f} m/s",
            "",
        ]

        if mean_err > 0.15:
            feedback.append(
                f"- **FB-V1**: Mean tracking error {mean_err:.3f} m/s is high. "
                f"Hypothesis: policy velocity command gain too low. "
                f"Recommendation: add stronger velocity tracking reward or increase "
                f"commanded speed gain in training."
            )
        if mean_std > 0.10:
            feedback.append(
                f"- **FB-V2**: High velocity oscillation (std={mean_std:.3f} m/s). "
                f"Suggests limit cycling. Check action smoothing or add velocity "
                f"variance penalty to reward."
            )

    if design_max and max_stable < design_max * 0.80:
        gap = design_max - max_stable
        feedback.append(
            f"- **FB-V3**: Max stable speed ({max_stable:.2f} m/s) is "
            f"{gap:.2f} m/s below design target ({design_max:.2f} m/s). "
            f"Recommendation: (a) increase max speed curriculum in training, "
            f"(b) check motor torque limits, (c) revisit foot contact model friction."
        )

    # Oscillation check per speed level
    for trial in stable_trials:
        vx_arr = np.array([s["vx_mps"] for s in trial["records"]])
        # Simple frequency check via zero-crossing rate
        centered = vx_arr - vx_arr.mean()
        crossings = np.where(np.diff(np.sign(centered)))[0]
        osc_freq  = len(crossings) / (2 * r["hold_duration_s"])
        if osc_freq > 5.0:
            feedback.append(
                f"- **FB-V4 [{trial['target_mps']}m/s]**: Velocity oscillation at "
                f"~{osc_freq:.1f} Hz detected. May indicate control instability at "
                f"this speed. Reduce action rate or add low-pass filter."
            )

    lines += ["", "## Design Feedback", ""]
    if feedback:
        lines += feedback
    else:
        lines.append("- Speed tracking within acceptable bounds. No design changes required.")

    lines += ["", "_Generated by analyze.py — Test 06 Speed_"]

    Path(out_path).write_text("\n".join(lines))
    print(f"Report written → {out_path}")
    print(f"Max stable: {max_stable:.2f} m/s  |  Design target: {design_max} m/s")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results.json")
    ap.add_argument("--out",     default="report.md")
    args = ap.parse_args()
    main(args.results, args.out)
