"""
Test 07: Disturbance Rejection Analysis
Computes fall rate, max tilt, recovery time per disturbance type.

Usage: python analyze.py [--results results.json] [--out report.md]
"""
import json
import argparse
import numpy as np
from pathlib import Path


def recovery_time(post_records, tilt_thresh_deg=5.0):
    """Seconds until tilt < tilt_thresh_deg and stays there."""
    if not post_records:
        return None
    t0 = post_records[0].get("t", 0)
    for rec in post_records:
        tilt = max(abs(rec.get("roll_deg", 0)), abs(rec.get("pitch_deg", 0)))
        if tilt < tilt_thresh_deg:
            return float(rec.get("t", t0) - t0)
    return None   # never recovered


def main(results_path: str, out_path: str):
    with open(results_path) as f:
        r = json.load(f)

    trials_map = r["trials"]
    feedback   = []

    lines = [
        "# Test 07 — Disturbance Rejection Analysis Report",
        "",
        f"**Walk speed**: {r['walk_speed_mps']} m/s  |  "
        f"**Trials per type**: {r['n_trials_per_type']}",
        "",
        "## Summary by Disturbance Type",
        "",
        "| Type | Falls | Fall Rate | Max Tilt (°) | Recovery Time (s) |",
        "|------|-------|-----------|-------------|-------------------|",
    ]

    for dist_type, trials in trials_map.items():
        n_trials   = len(trials)
        n_falls    = sum(1 for t in trials if t["fell"])
        fall_rate  = n_falls / n_trials if n_trials else 0
        max_tilts  = [t["max_tilt_deg"] for t in trials if not t["fell"]]
        avg_tilt   = float(np.mean(max_tilts)) if max_tilts else 0.0
        max_tilt   = float(np.max(max_tilts))  if max_tilts else 0.0

        rec_times = []
        for trial in trials:
            if not trial["fell"]:
                rt = recovery_time(trial.get("post_records", []))
                if rt is not None:
                    rec_times.append(rt)
        rec_str = f"{np.mean(rec_times):.2f}" if rec_times else "—"

        status = "✗" if n_falls > 0 else "✓"
        lines.append(
            f"| {dist_type} | {n_falls}/{n_trials} | {fall_rate:.0%} | "
            f"{max_tilt:.1f} | {rec_str} | {status} |"
        )

        if fall_rate > 0:
            feedback.append(
                f"- **FB-D{len(feedback)+1} [{dist_type}]**: {n_falls}/{n_trials} falls "
                f"({fall_rate:.0%} rate). "
                f"Recommendation: add disturbance curriculum — train with random "
                f"force impulses matching {dist_type} profile in sim."
            )
        elif avg_tilt > 20:
            feedback.append(
                f"- **FB-D{len(feedback)+1} [{dist_type}]**: High max tilt "
                f"({max_tilt:.1f}°) with no falls — policy recovers but with "
                f"large excursions. Add recovery reward shaping."
            )
        if rec_times and np.mean(rec_times) > 2.0:
            feedback.append(
                f"- **FB-D{len(feedback)+1} [{dist_type}]**: Slow recovery "
                f"({np.mean(rec_times):.2f}s avg). Policy may lack agility under "
                f"disturbance. Increase disturbance recovery training."
            )

    lines += [
        "",
        "## Design Feedback",
        "",
    ]
    if feedback:
        lines += feedback
    else:
        lines.append("- Disturbance rejection within acceptable bounds.")

    lines += [
        "",
        "## Recommendations",
        "",
        "For high fall rate (>20%):",
        "1. Add external force domain randomization to training (sim `push_robot` wrapper).",
        "2. Train explicit recovery behavior from fallen state.",
        "3. Reduce target walk speed until stability margin is verified.",
        "",
        "For payload disturbances (>20% mass change):",
        "1. Add mass randomization (±30%) in training.",
        "2. Review CoM estimation in state estimator.",
        "",
        "_Generated by analyze.py — Test 07 Disturbance_",
    ]

    Path(out_path).write_text("\n".join(lines))
    print(f"Report written → {out_path}")
    total_falls = sum(
        sum(1 for t in ts if t["fell"]) for ts in trials_map.values()
    )
    total_trials = sum(len(ts) for ts in trials_map.values())
    print(f"Total falls: {total_falls}/{total_trials}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results.json")
    ap.add_argument("--out",     default="report.md")
    args = ap.parse_args()
    main(args.results, args.out)
